package com.aiinterviewcoach.modules.ai.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import com.aiinterviewcoach.modules.ai.dto.AiEvaluationResponse;

@Service
public class GeminiEvaluationServiceImpl implements AiEvaluationService {

	private final WebClient webClient;

	@Value("${gemini.api.key}")
	private String apiKey;

	@Value("${gemini.api.url}")
	private String geminiUrl;

	public GeminiEvaluationServiceImpl(WebClient.Builder webClientBuilder) {
		this.webClient = webClientBuilder.build();
	}

	@Override
	public AiEvaluationResponse evaluateAnswer(String question, String userAnswer, String topic, String targetRole,
			String experienceLevel) {

		String prompt = """
				You are a senior technical interviewer.

				Evaluate the candidate answer.

				Topic: %s
				Target Role: %s
				Experience Level: %s

				Question:
				%s

				Candidate Answer:
				%s

				Return only in this format:
				SCORE: number out of 10
				FEEDBACK: short feedback
				IMPROVED_ANSWER: improved interview answer
				""".formatted(topic, targetRole, experienceLevel, question, userAnswer);

		String requestBody = """
				{
				  "contents": [
				    {
				      "parts": [
				        {
				          "text": "%s"
				        }
				      ]
				    }
				  ]
				}
				""".formatted(prompt.replace("\"", "\\\"").replace("\n", "\\n"));

		String response = webClient.post().uri(geminiUrl + "?key=" + apiKey).header("Content-Type", "application/json")
				.bodyValue(requestBody).retrieve().bodyToMono(String.class).block();

		return parseGeminiResponse(response);
	}

	private AiEvaluationResponse parseGeminiResponse(String response) {

		String text = response;

		int score = 6;
		String feedback = "AI feedback generated successfully.";
		String improvedAnswer = "Improved answer generated by AI.";

		if (text != null && text.contains("SCORE:")) {
			try {
				String scoreText = text.substring(text.indexOf("SCORE:") + 6).trim();
				scoreText = scoreText.split("\\n")[0].trim();
				score = Integer.parseInt(scoreText.replaceAll("[^0-9]", ""));
			} catch (Exception e) {
				score = 6;
			}
		}

		if (text != null && text.contains("FEEDBACK:")) {
			try {
				feedback = text.substring(text.indexOf("FEEDBACK:") + 9);
				if (feedback.contains("IMPROVED_ANSWER:")) {
					feedback = feedback.substring(0, feedback.indexOf("IMPROVED_ANSWER:")).trim();
				}
			} catch (Exception e) {
				feedback = "AI feedback generated successfully.";
			}
		}

		if (text != null && text.contains("IMPROVED_ANSWER:")) {
			improvedAnswer = text.substring(text.indexOf("IMPROVED_ANSWER:") + 16).trim();
		}

		return new AiEvaluationResponse(score, feedback, improvedAnswer);
	}
}
